### ISSUE TITLE
Test: Fix GRPC CI test 

### ISSUE THREAD

**Issue by TheCharlatan** [farcaster-project/farcaster-node#587]
The GRPC test address probably needs to be able to handle ipv6.

**Comment by h4sh3d** [comment]
We have this log often
```
thread 'tokio-runtime-worker' panicked at 'error running grpc server: tonic::transport::Error(Transport, hyper::Error(Listen, Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }))', src/grpcd/runtime.rs:202:14
```
maybe it's also because of the port number... (I thought it's about ipv6 but maybe not, we will have to check both)

**Comment by h4sh3d** [comment]
Another example in this [test case](https://github.com/farcaster-project/farcaster-node/runs/7518980096?check_suite_focus=true)

```
thread 'tokio-runtime-worker' panicked at 'error running grpc server: tonic::transport::Error(Transport, hyper::Error(Listen, Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }))', src/grpcd/runtime.rs:202:14
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::expect
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1035:23
   4: farcaster_node::grpcd::runtime::server_loop::{{closure}}
             at ./src/grpcd/runtime.rs:198:9
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
   7: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:165:17
   8: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/loom/std/unsafe_cell.rs:14:9
   9: tokio::runtime::task::core::CoreStage<T>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:155:13
  10: tokio::runtime::task::harness::poll_future::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:470:19
  11: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panic/unwind_safe.rs:271:9
  12: std::panicking::try::do_call
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
  13: __rust_try
  14: std::panicking::try
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
  15: std::panic::catch_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
  16: tokio::runtime::task::harness::poll_future
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:458:18
  17: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:104:27
  18: tokio::runtime::task::harness::Harness<T,S>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:57:15
  19: tokio::runtime::task::raw::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:144:5
  20: tokio::runtime::task::raw::RawTask::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:84:18
  21: tokio::runtime::task::LocalNotified<S>::run
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/mod.rs:376:9
  22: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:431:13
  23: tokio::coop::with_budget::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:102:9
  24: std::thread::local::LocalKey<T>::try_with
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/thread/local.rs:445:16
  25: std::thread::local::LocalKey<T>::with
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/thread/local.rs:421:9
  26: tokio::coop::with_budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:95:5
  27: tokio::coop::budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:72:5
  28: tokio::runtime::thread_pool::worker::Context::run_task
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:430:9
  29: tokio::runtime::thread_pool::worker::Context::run
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:397:24
  30: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:382:17
  31: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/macros/scoped_tls.rs:61:9
  32: tokio::runtime::thread_pool::worker::run
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:379:5
  33: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:358:45
  34: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/task.rs:42:21
  35: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:165:17
  36: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/loom/std/unsafe_cell.rs:14:9
  37: tokio::runtime::task::core::CoreStage<T>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:155:13
  38: tokio::runtime::task::harness::poll_future::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:470:19
  39: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panic/unwind_safe.rs:271:9
  40: std::panicking::try::do_call
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
  41: __rust_try
  42: std::panicking::try
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
  43: std::panic::catch_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
  44: tokio::runtime::task::harness::poll_future
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:458:18
  45: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:104:27
  46: tokio::runtime::task::harness::Harness<T,S>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:57:15
  47: tokio::runtime::task::raw::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:144:5
  48: tokio::runtime::task::raw::RawTask::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:84:18
  49: tokio::runtime::task::UnownedTask<S>::run
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/mod.rs:413:9
  50: tokio::runtime::blocking::pool::Task::run
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:91:9
  51: tokio::runtime::blocking::pool::Inner::run
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:325:17
  52: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:300:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2022-07-26T11:25:01Z WARN  farcaster_node::grpcd::runtime] exiting grpc server run routine with: Err(JoinError::Panic(Id(6), ...))
[2022-07-26T11:25:02Z INFO  farcaster_node::service] New service grpcd started
[2022-07-26T11:25:02Z DEBUG microservices::esb::controller] grpcd -> farcasterd: hello()
[2022-07-26T11:25:02Z INFO  farcaster_node::farcasterd::runtime] Service grpcd is now connected
[2022-07-26T11:25:02Z DEBUG microservices::esb::controller] grpcd -> farcasterd: hello()
```
It's weird that `grpcd` still answer `hello` back to `farcasterd`.
